substitutions:
  name: xiaozhi-muma
  friendly_name: "Xiaozhi Muma Box v1"

## Modular version Main SENDSPIN edition

## SETTINGS ######################################################################################################################################

  imagewidth:  "240"
  imageheight: "240"

  screenwidth:  "240"
  screenheight: "240"
  rotate_display: "0"

  startup_sound: "Home_Connected" # (options are: available, Home_Connected, Home_Connected_Male, Computer_Ready)
  wakeup_sound: "popup" # (options are: popup, wake_word_triggered)
  clock_background_image: "chip" # (options are: clock, hacker, mission, starrysky, waves, tron, chip, waterdrops)
  imagemodel: "Gwen" # options are:

# AlbertQuackmore, Alita, Alfred, Astrobot, Buzz, Casita, Cybergirl, Dory, EVE, Eyes, Eyes2, GLaDOS, Girl1, Guy1, Guy2, Gwen, HA-character, ha-girl, Hacker, Harley,
# Jarvis, Luffy, Mario, Max, Prime, Robochibi, Robocop, Robot, Robotgirl, Salem, Sarah, Shaun

# USE ONLINE OR LOCAL MODEL AND WALLPAPER IMAGES, IMAGES SHOULD BE PLACED IN: homeassistant/www/images/
  imagepath: "https://github.com/RealDeco/xiaozhi-esphome/raw/main/images"
#  imagepath: "http://homeassistant.local:8123/local/images/"

## PRESENCE / MOTION SENSORS ########## IF NOT USING THESE LEAVE THEM ALONE, SCRIPT WILL BREAK WITHOUT ###########################################

  sensor1_entity: "binary_sensor.room_1_presence"
  light1_entity: "binary_sensor.room_1_light"
  sensor1_label: "Room 1"

  sensor2_entity: "binary_sensor.room_2_presence"
  light2_entity: "binary_sensor.room_2_light"
  sensor2_label: "Room 2"

  sensor3_entity: "binary_sensor.room_3_presence"
  light3_entity: "binary_sensor.room_3_light"
  sensor3_label: "Room 3"

  sensor4_entity: "binary_sensor.room_4_presence"
  light4_entity: "binary_sensor.room_4_light"
  sensor4_label: "Room 4"

  sensor5_entity: "binary_sensor.room_5_presence"
  light5_entity: "binary_sensor.room_5_light"
  sensor5_label: "Room 5"

  weather_entity: "weather.forecast_home"

##################################################################################################################################################

  font_glyphsets: "GF_Latin_Core"
  font_family: Figtree

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2026.5.0
  name_add_mac_suffix: true
  project:
    name: realdeco.xiaozhi-esphome
    version: "2026.5.0"

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

wifi:
  ap:

improv_serial:

### USE MODULES FROM GITHUB (default) ############################################################################################################

packages:
  core:
    url: https://github.com/RealDeco/xiaozhi-esphome.git
    ref: main
    refresh: 0s
    files:
      - devices/Under_Development/Modular/core-sendspin.yaml
  hw:
    url: https://github.com/RealDeco/xiaozhi-esphome.git
    ref: main
    refresh: 0s
    files:
      - devices/Under_Development/Modular/HW/muma-sendspin_hw.yaml
  extcomp:
    url: https://github.com/RealDeco/xiaozhi-esphome.git
    ref: main
    refresh: 0s
    files:
      - devices/Under_Development/Modular/HW/sendspin-external_components.yaml

### USE LOCAL MODULES (read description https://github.com/RealDeco/xiaozhi-esphome/blob/main/devices/Under_Development/Modular/README.md) #######

#packages: # Local
#  core: !include localtest/core-sendspin.yaml
#  hw:   !include localtest/HW/muma-sendspin_hw.yaml
#  extcomp:   !include localtest/HW/sendspin-external_components.yaml

# Debug logging, Uncomment ONLY if debugging, defaults to WARN
#logger:
#  level: DEBUG

## ENABLE / DISABLE WAKE WORDS ## IF LOW ON MEMORY, USE LESS WAKE WORDS ##########################################################################

micro_wake_word:
  id: mww
  models:
    - okay_nabu
    - hey_jarvis
#    - alexa
#    - hey_mycroft
#    - model: https://raw.githubusercontent.com/RealDeco/xiaozhi-esphome/refs/heads/main/MicroWakeWords/models/v2/hey_sarah.json
#    - model: https://raw.githubusercontent.com/JohnnyPrimus/Custom_V2_MicroWakeWords/refs/heads/main/models/computer/computer.json
#    - model: https://raw.githubusercontent.com/JohnnyPrimus/Custom_V2_MicroWakeWords/refs/heads/main/models/hey_friday/hey_friday.json
#    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241226.3/okay_nabu.json
#    - model: https://raw.githubusercontent.com/formatBCE/Respeaker-Lite-ESPHome-integration/refs/heads/main/microwakeword/models/v2/kenobi.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/choo_choo_homie.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/hey_home_assistant.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/hey_peppa_pig.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/okay_computer.json

##################################################################################################################################################
